# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from av_msgs/IbeoPoint.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class IbeoPoint(genpy.Message):
  _md5sum = "9be76836bccda774e0c4ed9114e101d6"
  _type = "av_msgs/IbeoPoint"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 device_id
uint8 echo
uint16 flags
uint8 layer
float32 position_x
float32 position_y
float32 position_z
"""
  __slots__ = ['device_id','echo','flags','layer','position_x','position_y','position_z']
  _slot_types = ['uint8','uint8','uint16','uint8','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       device_id,echo,flags,layer,position_x,position_y,position_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IbeoPoint, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.device_id is None:
        self.device_id = 0
      if self.echo is None:
        self.echo = 0
      if self.flags is None:
        self.flags = 0
      if self.layer is None:
        self.layer = 0
      if self.position_x is None:
        self.position_x = 0.
      if self.position_y is None:
        self.position_y = 0.
      if self.position_z is None:
        self.position_z = 0.
    else:
      self.device_id = 0
      self.echo = 0
      self.flags = 0
      self.layer = 0
      self.position_x = 0.
      self.position_y = 0.
      self.position_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2BHB3f.pack(_x.device_id, _x.echo, _x.flags, _x.layer, _x.position_x, _x.position_y, _x.position_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.device_id, _x.echo, _x.flags, _x.layer, _x.position_x, _x.position_y, _x.position_z,) = _struct_2BHB3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2BHB3f.pack(_x.device_id, _x.echo, _x.flags, _x.layer, _x.position_x, _x.position_y, _x.position_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.device_id, _x.echo, _x.flags, _x.layer, _x.position_x, _x.position_y, _x.position_z,) = _struct_2BHB3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2BHB3f = struct.Struct("<2BHB3f")
