# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from av_msgs/RSDSObjectList.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import av_msgs.msg

class RSDSObjectList(genpy.Message):
  _md5sum = "7d986c7de0623b45f1b9ae898cef8ac3"
  _type = "av_msgs/RSDSObjectList"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint64 timestamp
RSDSObject[] radar_object_list
uint8[1240] ori_msg

================================================================================
MSG: av_msgs/RSDSObject
uint64 id # object id
float32 x_pos 
float32 x_vel
float32 x_acc
float32 y_pos
float32 y_vel
float32 y_acc
int32 tracker_status
int32 station_flags

"""
  __slots__ = ['timestamp','radar_object_list','ori_msg']
  _slot_types = ['uint64','av_msgs/RSDSObject[]','uint8[1240]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,radar_object_list,ori_msg

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RSDSObjectList, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.radar_object_list is None:
        self.radar_object_list = []
      if self.ori_msg is None:
        self.ori_msg = chr(0)*1240
    else:
      self.timestamp = 0
      self.radar_object_list = []
      self.ori_msg = chr(0)*1240

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_Q.pack(self.timestamp))
      length = len(self.radar_object_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.radar_object_list:
        _x = val1
        buff.write(_struct_Q6f2i.pack(_x.id, _x.x_pos, _x.x_vel, _x.x_acc, _x.y_pos, _x.y_vel, _x.y_acc, _x.tracker_status, _x.station_flags))
      _x = self.ori_msg
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_1240B.pack(*_x))
      else:
        buff.write(_struct_1240s.pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.radar_object_list is None:
        self.radar_object_list = None
      end = 0
      start = end
      end += 8
      (self.timestamp,) = _struct_Q.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.radar_object_list = []
      for i in range(0, length):
        val1 = av_msgs.msg.RSDSObject()
        _x = val1
        start = end
        end += 40
        (_x.id, _x.x_pos, _x.x_vel, _x.x_acc, _x.y_pos, _x.y_vel, _x.y_acc, _x.tracker_status, _x.station_flags,) = _struct_Q6f2i.unpack(str[start:end])
        self.radar_object_list.append(val1)
      start = end
      end += 1240
      self.ori_msg = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_Q.pack(self.timestamp))
      length = len(self.radar_object_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.radar_object_list:
        _x = val1
        buff.write(_struct_Q6f2i.pack(_x.id, _x.x_pos, _x.x_vel, _x.x_acc, _x.y_pos, _x.y_vel, _x.y_acc, _x.tracker_status, _x.station_flags))
      _x = self.ori_msg
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_struct_1240B.pack(*_x))
      else:
        buff.write(_struct_1240s.pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.radar_object_list is None:
        self.radar_object_list = None
      end = 0
      start = end
      end += 8
      (self.timestamp,) = _struct_Q.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.radar_object_list = []
      for i in range(0, length):
        val1 = av_msgs.msg.RSDSObject()
        _x = val1
        start = end
        end += 40
        (_x.id, _x.x_pos, _x.x_vel, _x.x_acc, _x.y_pos, _x.y_vel, _x.y_acc, _x.tracker_status, _x.station_flags,) = _struct_Q6f2i.unpack(str[start:end])
        self.radar_object_list.append(val1)
      start = end
      end += 1240
      self.ori_msg = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_Q = struct.Struct("<Q")
_struct_1240B = struct.Struct("<1240B")
_struct_1240s = struct.Struct("<1240s")
_struct_Q6f2i = struct.Struct("<Q6f2i")
