# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from av_msgs/IbeoObjectList.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import av_msgs.msg

class IbeoObjectList(genpy.Message):
  _md5sum = "981f29f62d860aaf5829de1d977ef990"
  _type = "av_msgs/IbeoObjectList"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint64 timestamp
IbeoObject[] ibeo_object_list

================================================================================
MSG: av_msgs/IbeoObject
uint16 object_id
float32 object_box_center_x
float32 object_box_center_y
float32 object_box_length
float32 object_box_width
float32 object_box_orientation
float32 relative_velocity_x
float32 relative_velocity_y
float32 relative_velocity_sigma_x
float32 relative_velocity_sigma_y
uint8 object_class
float32 object_class_certainty
float32 exist_measurement


"""
  __slots__ = ['timestamp','ibeo_object_list']
  _slot_types = ['uint64','av_msgs/IbeoObject[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,ibeo_object_list

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IbeoObjectList, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.ibeo_object_list is None:
        self.ibeo_object_list = []
    else:
      self.timestamp = 0
      self.ibeo_object_list = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_Q.pack(self.timestamp))
      length = len(self.ibeo_object_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.ibeo_object_list:
        _x = val1
        buff.write(_struct_H9fB2f.pack(_x.object_id, _x.object_box_center_x, _x.object_box_center_y, _x.object_box_length, _x.object_box_width, _x.object_box_orientation, _x.relative_velocity_x, _x.relative_velocity_y, _x.relative_velocity_sigma_x, _x.relative_velocity_sigma_y, _x.object_class, _x.object_class_certainty, _x.exist_measurement))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.ibeo_object_list is None:
        self.ibeo_object_list = None
      end = 0
      start = end
      end += 8
      (self.timestamp,) = _struct_Q.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ibeo_object_list = []
      for i in range(0, length):
        val1 = av_msgs.msg.IbeoObject()
        _x = val1
        start = end
        end += 47
        (_x.object_id, _x.object_box_center_x, _x.object_box_center_y, _x.object_box_length, _x.object_box_width, _x.object_box_orientation, _x.relative_velocity_x, _x.relative_velocity_y, _x.relative_velocity_sigma_x, _x.relative_velocity_sigma_y, _x.object_class, _x.object_class_certainty, _x.exist_measurement,) = _struct_H9fB2f.unpack(str[start:end])
        self.ibeo_object_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_Q.pack(self.timestamp))
      length = len(self.ibeo_object_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.ibeo_object_list:
        _x = val1
        buff.write(_struct_H9fB2f.pack(_x.object_id, _x.object_box_center_x, _x.object_box_center_y, _x.object_box_length, _x.object_box_width, _x.object_box_orientation, _x.relative_velocity_x, _x.relative_velocity_y, _x.relative_velocity_sigma_x, _x.relative_velocity_sigma_y, _x.object_class, _x.object_class_certainty, _x.exist_measurement))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.ibeo_object_list is None:
        self.ibeo_object_list = None
      end = 0
      start = end
      end += 8
      (self.timestamp,) = _struct_Q.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ibeo_object_list = []
      for i in range(0, length):
        val1 = av_msgs.msg.IbeoObject()
        _x = val1
        start = end
        end += 47
        (_x.object_id, _x.object_box_center_x, _x.object_box_center_y, _x.object_box_length, _x.object_box_width, _x.object_box_orientation, _x.relative_velocity_x, _x.relative_velocity_y, _x.relative_velocity_sigma_x, _x.relative_velocity_sigma_y, _x.object_class, _x.object_class_certainty, _x.exist_measurement,) = _struct_H9fB2f.unpack(str[start:end])
        self.ibeo_object_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_Q = struct.Struct("<Q")
_struct_H9fB2f = struct.Struct("<H9fB2f")
