# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from av_msgs/Object3D.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Object3D(genpy.Message):
  _md5sum = "b61e17d31f6a6546d41ab0932afcccd8"
  _type = "av_msgs/Object3D"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 class_id
float32 center_x
float32 center_y
float32 center_z
float32 length
float32 width
float32 height
float32 orient
float32 confidence
"""
  __slots__ = ['class_id','center_x','center_y','center_z','length','width','height','orient','confidence']
  _slot_types = ['uint8','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       class_id,center_x,center_y,center_z,length,width,height,orient,confidence

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Object3D, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.class_id is None:
        self.class_id = 0
      if self.center_x is None:
        self.center_x = 0.
      if self.center_y is None:
        self.center_y = 0.
      if self.center_z is None:
        self.center_z = 0.
      if self.length is None:
        self.length = 0.
      if self.width is None:
        self.width = 0.
      if self.height is None:
        self.height = 0.
      if self.orient is None:
        self.orient = 0.
      if self.confidence is None:
        self.confidence = 0.
    else:
      self.class_id = 0
      self.center_x = 0.
      self.center_y = 0.
      self.center_z = 0.
      self.length = 0.
      self.width = 0.
      self.height = 0.
      self.orient = 0.
      self.confidence = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B8f.pack(_x.class_id, _x.center_x, _x.center_y, _x.center_z, _x.length, _x.width, _x.height, _x.orient, _x.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.class_id, _x.center_x, _x.center_y, _x.center_z, _x.length, _x.width, _x.height, _x.orient, _x.confidence,) = _struct_B8f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B8f.pack(_x.class_id, _x.center_x, _x.center_y, _x.center_z, _x.length, _x.width, _x.height, _x.orient, _x.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.class_id, _x.center_x, _x.center_y, _x.center_z, _x.length, _x.width, _x.height, _x.orient, _x.confidence,) = _struct_B8f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B8f = struct.Struct("<B8f")
