# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from av_msgs/VehicleState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VehicleState(genpy.Message):
  _md5sum = "cf167c65e8246be405f6d862a2d02a6d"
  _type = "av_msgs/VehicleState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint64 timestamp
float64 x
float64 y
float64 ang
float64 vel_x
float64 vel_y
float64 vel_ang
float64 acc_x
float64 acc_y
float64 acc_ang
float64 ref_curvature
"""
  __slots__ = ['timestamp','x','y','ang','vel_x','vel_y','vel_ang','acc_x','acc_y','acc_ang','ref_curvature']
  _slot_types = ['uint64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,x,y,ang,vel_x,vel_y,vel_ang,acc_x,acc_y,acc_ang,ref_curvature

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = 0
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.ang is None:
        self.ang = 0.
      if self.vel_x is None:
        self.vel_x = 0.
      if self.vel_y is None:
        self.vel_y = 0.
      if self.vel_ang is None:
        self.vel_ang = 0.
      if self.acc_x is None:
        self.acc_x = 0.
      if self.acc_y is None:
        self.acc_y = 0.
      if self.acc_ang is None:
        self.acc_ang = 0.
      if self.ref_curvature is None:
        self.ref_curvature = 0.
    else:
      self.timestamp = 0
      self.x = 0.
      self.y = 0.
      self.ang = 0.
      self.vel_x = 0.
      self.vel_y = 0.
      self.vel_ang = 0.
      self.acc_x = 0.
      self.acc_y = 0.
      self.acc_ang = 0.
      self.ref_curvature = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_Q10d.pack(_x.timestamp, _x.x, _x.y, _x.ang, _x.vel_x, _x.vel_y, _x.vel_ang, _x.acc_x, _x.acc_y, _x.acc_ang, _x.ref_curvature))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 88
      (_x.timestamp, _x.x, _x.y, _x.ang, _x.vel_x, _x.vel_y, _x.vel_ang, _x.acc_x, _x.acc_y, _x.acc_ang, _x.ref_curvature,) = _struct_Q10d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_Q10d.pack(_x.timestamp, _x.x, _x.y, _x.ang, _x.vel_x, _x.vel_y, _x.vel_ang, _x.acc_x, _x.acc_y, _x.acc_ang, _x.ref_curvature))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 88
      (_x.timestamp, _x.x, _x.y, _x.ang, _x.vel_x, _x.vel_y, _x.vel_ang, _x.acc_x, _x.acc_y, _x.acc_ang, _x.ref_curvature,) = _struct_Q10d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_Q10d = struct.Struct("<Q10d")
