(cl:defpackage av_msgs-srv
  (:use )
  (:export
   "GETPOINTONROAD"
   "<GETPOINTONROAD-REQUEST>"
   "GETPOINTONROAD-REQUEST"
   "<GETPOINTONROAD-RESPONSE>"
   "GETPOINTONROAD-RESPONSE"
   "GETLOCALLANEMARKERS"
   "<GETLOCALLANEMARKERS-REQUEST>"
   "GETLOCALLANEMARKERS-REQUEST"
   "<GETLOCALLANEMARKERS-RESPONSE>"
   "GETLOCALLANEMARKERS-RESPONSE"
  ))

