// Generated by gencpp from file av_msgs/TrafficLightMapData.msg
// DO NOT EDIT!


#ifndef AV_MSGS_MESSAGE_TRAFFICLIGHTMAPDATA_H
#define AV_MSGS_MESSAGE_TRAFFICLIGHTMAPDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <av_msgs/TrafficLightLoc.h>

namespace av_msgs
{
template <class ContainerAllocator>
struct TrafficLightMapData_
{
  typedef TrafficLightMapData_<ContainerAllocator> Type;

  TrafficLightMapData_()
    : tl_map_list()  {
    }
  TrafficLightMapData_(const ContainerAllocator& _alloc)
    : tl_map_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::av_msgs::TrafficLightLoc_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::av_msgs::TrafficLightLoc_<ContainerAllocator> >::other >  _tl_map_list_type;
  _tl_map_list_type tl_map_list;




  typedef boost::shared_ptr< ::av_msgs::TrafficLightMapData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::av_msgs::TrafficLightMapData_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficLightMapData_

typedef ::av_msgs::TrafficLightMapData_<std::allocator<void> > TrafficLightMapData;

typedef boost::shared_ptr< ::av_msgs::TrafficLightMapData > TrafficLightMapDataPtr;
typedef boost::shared_ptr< ::av_msgs::TrafficLightMapData const> TrafficLightMapDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::av_msgs::TrafficLightMapData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::av_msgs::TrafficLightMapData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace av_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/jade/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'av_msgs': ['/home/zhouji/Documents/autodrive/rpc_ws/src/common/av_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::av_msgs::TrafficLightMapData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::av_msgs::TrafficLightMapData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::av_msgs::TrafficLightMapData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::av_msgs::TrafficLightMapData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::av_msgs::TrafficLightMapData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::av_msgs::TrafficLightMapData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::av_msgs::TrafficLightMapData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4a02ab3c37e7cabb4dd223f9294396e";
  }

  static const char* value(const ::av_msgs::TrafficLightMapData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4a02ab3c37e7cabULL;
  static const uint64_t static_value2 = 0xb4dd223f9294396eULL;
};

template<class ContainerAllocator>
struct DataType< ::av_msgs::TrafficLightMapData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "av_msgs/TrafficLightMapData";
  }

  static const char* value(const ::av_msgs::TrafficLightMapData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::av_msgs::TrafficLightMapData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TrafficLightLoc[] tl_map_list\n\
\n\
================================================================================\n\
MSG: av_msgs/TrafficLightLoc\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::av_msgs::TrafficLightMapData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::av_msgs::TrafficLightMapData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tl_map_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficLightMapData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::av_msgs::TrafficLightMapData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::av_msgs::TrafficLightMapData_<ContainerAllocator>& v)
  {
    s << indent << "tl_map_list[]" << std::endl;
    for (size_t i = 0; i < v.tl_map_list.size(); ++i)
    {
      s << indent << "  tl_map_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::av_msgs::TrafficLightLoc_<ContainerAllocator> >::stream(s, indent + "    ", v.tl_map_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AV_MSGS_MESSAGE_TRAFFICLIGHTMAPDATA_H
