(cl:in-package av_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          RAW_DATA-VAL
          RAW_DATA
          MTIME-VAL
          MTIME
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          VEL_X-VAL
          VEL_X
          VEL_Y-VAL
          VEL_Y
          VEL_Z-VAL
          VEL_Z
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          NAV_MODE-VAL
          NAV_MODE
          POS_MODE-VAL
          POS_MODE
          VEL_MODE-VAL
          VEL_MODE
          ATT_MODE-VAL
          ATT_MODE
          ANGULAR_VEL_X-VAL
          ANGULAR_VEL_X
          ANGULAR_VEL_Y-VAL
          ANGULAR_VEL_Y
          ANGULAR_VEL_Z-VAL
          ANGULAR_VEL_Z
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          POSE_X-VAL
          POSE_X
          POSE_Y-VAL
          POSE_Y
))