(cl:in-package av_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          RAW_DATA-VAL
          RAW_DATA
          MTIME-VAL
          MTIME
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          VEL_X-VAL
          VEL_X
          VEL_Y-VAL
          VEL_Y
          VEL_Z-VAL
          VEL_Z
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          NAV_MODE-VAL
          NAV_MODE
          POS_MODE-VAL
          POS_MODE
          VEL_MODE-VAL
          VEL_MODE
          ATT_MODE-VAL
          ATT_MODE
          YAW_X-VAL
          YAW_X
          YAW_Y-VAL
          YAW_Y
          YAW_Z-VAL
          YAW_Z
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
))