(cl:in-package av_msgs-msg)
(cl:export '(CLASS_ID-VAL
          CLASS_ID
          ID-VAL
          ID
          CENTER_X-VAL
          CENTER_X
          CENTER_Y-VAL
          CENTER_Y
          CENTER_Z-VAL
          CENTER_Z
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          LENGTH-VAL
          LENGTH
          VELOCITY-VAL
          VELOCITY
          HEADING-VAL
          HEADING
          OMEGA-VAL
          OMEGA
          ACCELERATION-VAL
          ACCELERATION
          SHIELD_TIME-VAL
          SHIELD_TIME
          VELOCITY_MEASUREMENT_COVARIANCE-VAL
          VELOCITY_MEASUREMENT_COVARIANCE
))