(cl:in-package av_msgs-msg)
(cl:export '(OBJECT_ID-VAL
          OBJECT_ID
          OBJECT_BOX_CENTER_X-VAL
          OBJECT_BOX_CENTER_X
          OBJECT_BOX_CENTER_Y-VAL
          OBJECT_BOX_CENTER_Y
          OBJECT_BOX_LENGTH-VAL
          OBJECT_BOX_LENGTH
          OBJECT_BOX_WIDTH-VAL
          OBJECT_BOX_WIDTH
          OBJECT_BOX_ORIENTATION-VAL
          OBJECT_BOX_ORIENTATION
          RELATIVE_VELOCITY_X-VAL
          RELATIVE_VELOCITY_X
          RELATIVE_VELOCITY_Y-VAL
          RELATIVE_VELOCITY_Y
          RELATIVE_VELOCITY_SIGMA_X-VAL
          RELATIVE_VELOCITY_SIGMA_X
          RELATIVE_VELOCITY_SIGMA_Y-VAL
          RELATIVE_VELOCITY_SIGMA_Y
          OBJECT_CLASS-VAL
          OBJECT_CLASS
          OBJECT_CLASS_CERTAINTY-VAL
          OBJECT_CLASS_CERTAINTY
          EXIST_MEASUREMENT-VAL
          EXIST_MEASUREMENT
))