(cl:defpackage av_msgs-srv
  (:use )
  (:export
   "GETLOCALLANEMARKERS"
   "<GETLOCALLANEMARKERS-REQUEST>"
   "GETLOCALLANEMARKERS-REQUEST"
   "<GETLOCALLANEMARKERS-RESPONSE>"
   "GETLOCALLANEMARKERS-RESPONSE"
  ))

