/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ros_CONSTANTS_H
#define ros_CONSTANTS_H

#include "ros_types.h"

namespace Ros {

class rosConstants {
 public:
  rosConstants();

};

extern const rosConstants g_ros_constants;

} // namespace

#endif
